apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project-staging

resources:
- ../../base
- route.yaml

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: broadcaster
    spec:
      template:
        spec:
          containers:
            - name: broadcaster
              env:
                - name: LOG_ONLY
                  value: "true"
                - name: NATS_SUBJECT
                  value: todos.events.staging
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: todo-backend
    spec:
      template:
        spec:
          containers:
            - name: todo-backend
              env:
                - name: NATS_SUBJECT
                  value: todos.events.staging
images:
- name: lindkon/broadcaster
  newName: lindkon/broadcaster
  newTag: 5a76dfdf45ceec1fb0c4fb043b800a877ae4db68
- name: lindkon/get-image
  newName: lindkon/get-image
  newTag: 5a76dfdf45ceec1fb0c4fb043b800a877ae4db68
- name: lindkon/todo-backend
  newName: lindkon/todo-backend
  newTag: 5a76dfdf45ceec1fb0c4fb043b800a877ae4db68
- name: lindkon/todo-main
  newName: lindkon/todo-main
  newTag: 5a76dfdf45ceec1fb0c4fb043b800a877ae4db68
