apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project-staging

resources:
- ../../base
- route.yaml

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: broadcaster
    spec:
      template:
        spec:
          containers:
            - name: broadcaster
              env:
                - name: LOG_ONLY
                  value: "true"
                - name: NATS_SUBJECT
                  value: todos.events.staging
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: todo-backend
    spec:
      template:
        spec:
          containers:
            - name: todo-backend
              env:
                - name: NATS_SUBJECT
                  value: todos.events.staging
images:
- name: lindkon/broadcaster
  newName: lindkon/broadcaster
  newTag: b36471ac3910dea4aaa1c04e8b0d0cb9b3fa4f9d
- name: lindkon/get-image
  newName: lindkon/get-image
  newTag: b36471ac3910dea4aaa1c04e8b0d0cb9b3fa4f9d
- name: lindkon/todo-backend
  newName: lindkon/todo-backend
  newTag: b36471ac3910dea4aaa1c04e8b0d0cb9b3fa4f9d
- name: lindkon/todo-main
  newName: lindkon/todo-main
  newTag: b36471ac3910dea4aaa1c04e8b0d0cb9b3fa4f9d
