apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-app-config
data:
  PORT: "3001"
  FILES_DIR: "/usr/src/app/files"
  IMAGE_FILENAME: "image.jpg"
  IMAGE_SOURCE_URL: "https://picsum.photos/1200"
  MAX_IMAGE_AGE_MS: "600000"
  CHECK_INTERVAL_MS: "60000"