apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project-prod

resources:
- ../../base
- backup.yaml
- backup-pvc.yaml
- route.yaml

images:
- name: lindkon/broadcaster
  newTag: e0d0d935050fef29f6ca70d1c59e1ed084ee5048
- name: lindkon/get-image
  newTag: e0d0d935050fef29f6ca70d1c59e1ed084ee5048
- name: lindkon/todo-backend
  newTag: e0d0d935050fef29f6ca70d1c59e1ed084ee5048
- name: lindkon/todo-main
  newTag: e0d0d935050fef29f6ca70d1c59e1ed084ee5048
