apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project-prod

resources:
- ../../base
- backup.yaml
- backup-pvc.yaml
- route.yaml

images:
- name: lindkon/broadcaster
  newTag: b36471ac3910dea4aaa1c04e8b0d0cb9b3fa4f9d
- name: lindkon/get-image
  newTag: b36471ac3910dea4aaa1c04e8b0d0cb9b3fa4f9d
- name: lindkon/todo-backend
  newTag: b36471ac3910dea4aaa1c04e8b0d0cb9b3fa4f9d
- name: lindkon/todo-main
  newTag: b36471ac3910dea4aaa1c04e8b0d0cb9b3fa4f9d
