apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project-prod

resources:
- ../../base
- backup.yaml
- backup-pvc.yaml
- route.yaml

images:
- name: lindkon/broadcaster
  newTag: fb960d47d5413b3f60d6f8115c741bab2bd6dec6
- name: lindkon/get-image
  newTag: fb960d47d5413b3f60d6f8115c741bab2bd6dec6
- name: lindkon/todo-backend
  newTag: fb960d47d5413b3f60d6f8115c741bab2bd6dec6
- name: lindkon/todo-main
  newTag: fb960d47d5413b3f60d6f8115c741bab2bd6dec6
