apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  ### IMPORTANT ###
  # Secrets are not in kustomize, must be deployed manually when changed.

resources:
- ../manifests
- ../todo-app/manifests
- ../todo-backend/manifests
- ../broadcaster/manifests

